#!/bin/sh
#
# Loader script for any plugins which contain a prepare-commit-msg hook.

# shellcheck source=/usr/local/Cellar/git/2.15.1/libexec/git-core/git-sh-setup
. "$(git --exec-path)/git-sh-setup"

# shellcheck disable=SC1090
. "$GIT_DIR/hooks/hooky.sh"
hooky "prepare-commit-msg" "$@"
